### PR TITLE
Course discovery service customization

### PR DESCRIPTION
**Pull request by avadhuts-perpetual**
API:
   1) Change generic REST pagination to use page based pagination.
   2) Add enable_jvc, room_key and display_organization fields in course_run model/api.
      Modified course_run serializer, data_loader for courses v1 api for above changes.
   3) Change authentication class for management api.

Course Metadata:
   1) Fixed token_type parameter issue in management api.
   2) Changed short description field type to text in course and course_run
   3) Change key 'id' to 'course_id' in course api reponse's body dictionary.

Settings:
   1) The yml setting file overiding implementation is changed to support dictionary and variable.
   2) Added settings config example file.

### CODE REVIEW

**Comment by rohit-k** [comment]
@avadhuts-perpetual : course_discovery_settings.yml -> Is this file added due to backport from master?

**Comment by avadhuts-perpetual** [comment]
@rohit-k

  The default implementation use the yml file, the path of yml file should be set in env variable. https://github.com/JioEducation/course-discovery/blob/master/course_discovery/settings/production.py#L22 

I have customized implementation to support dictionary values also, Its not same like JSON file override in edx-platform though , if value is dictionary or nested dictionary then setting file should have all key and values mention in base.py  https://github.com/JioEducation/course-discovery/blob/master/course_discovery/settings/base.py. 

Currently only required settings are override.
https://github.com/JioEducation/course-discovery/pull/2/files#diff-dfab13f51782950a9e6f467219220ae9R20

**Comment by rohit-k** [comment]
Rename course_discovery_settings.yml  to course_discovery_settings.yml,example

**Comment by rohit-k** [comment]
Approved for merging. Please re-test after deployment.

**Pull request merged**
